export const routerMap = {
    HOME: '/',
    SIGNUP: 'signUp',
    LOGIN: 'login',
    CATALOG: 'catalog',
    VENUE_DETAIL: 'catalog/venue/:venueId',
    CONVENTION_DETAIL: 'catalog/convention/:conventionId',
    CALENDAR: 'calendar',
    MAPS: 'maps',
    CREATE: 'create',
    EDIT: 'edit',
    MENU: 'menu',
    ABOUT: 'about',
    HELP: 'help',
    Event_BUILDER: 'eventBuilder',
}